//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medness.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogueXmlNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogueXmlNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medness.Infrastructure.DialogueXmlNames", typeof(DialogueXmlNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue.
        /// </summary>
        internal static string Dialogue {
            get {
                return ResourceManager.GetString("Dialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogueItem.
        /// </summary>
        internal static string DialogueItem {
            get {
                return ResourceManager.GetString("DialogueItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string DialogueItemCharacter {
            get {
                return ResourceManager.GetString("DialogueItemCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFile.
        /// </summary>
        internal static string DialogueItemDataFile {
            get {
                return ResourceManager.GetString("DialogueItemDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string DialogueItemId {
            get {
                return ResourceManager.GetString("DialogueItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string DialogueItemText {
            get {
                return ResourceManager.GetString("DialogueItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogueTrigger.
        /// </summary>
        internal static string DialogueTrigger {
            get {
                return ResourceManager.GetString("DialogueTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string DialogueTriggerObject {
            get {
                return ResourceManager.GetString("DialogueTriggerObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DialogueTriggerType {
            get {
                return ResourceManager.GetString("DialogueTriggerType", resourceCulture);
            }
        }
    }
}
